#!/bin/bash
# Copyright (C) 2026 Zoran Loncarevic

arg0=${0##*/}
: "${REPOSITORY_DIR:=$HOME/Projects/Chez/Repository}"
connected_to_terminal=$([[ -t 0 ]] && echo yes || echo no)

function usage() {
  echo "Usage: $arg0 [options] command ..."
  exit 0
}

function version() {
  echo "$arg0 version 0.1"
  exit 0
}

function perror() {
  echo $1
  if [[ "$2" != "non-fatal" ]]; then
    exit 1
  fi
}

function verbose_message()
{
  if [[ "$option_verbose" == "yes" ]]; then
    echo "+$1"
  fi
}

function save_options()
{
  local option_var
  while [[ $# -gt 0 ]]; do
    option_var="option_$1"
    printf -v "saved_$option_var" "%s" "${!option_var}"
    shift
  done
}

function restore_options()
{
  local option_var
  while [[ $# -gt 0 ]]; do
    option_var="saved_option_$1"
    printf -v "option_$1" "%s" "${!option_var}"
    shift
  done
}

function is_this_a_dry_run()
{
  [[ "$option_dry_run" == "yes" ]]
}

function system_to_repository()
{
  local repository=${1/#$HOME//HOME}

  repository=${repository///dot_//literal_dot_}
  repository=${repository///.//dot_}

  echo $repository
}

function repository_to_system()
{
  local system=${1#$REPOSITORY_DIR/Files}

  system=${system/#\/HOME\//$HOME\/}
  system=${system///dot_//.}
  system=${system///literal_//}
  echo $system
}

function for_each_found_file_do()
{
  local callback=$1
  shift

  while IFS= read -r -d '' file; do
    "$callback" "$file"
  done < <(find "$@" -print0)
}

function for_each_found_file_with_options_slurped_do()
{
  local file attribute value line
  local prev_file=""
  local failure_cnt=0

  local callback=$1
  shift

  local relevant_attributes=(symbolic test)
  save_options "${relevant_attributes[@]}"

  local excluded_files="! -name .gitkeep ! -name .gitattributes"
  find "$@" $excluded_files |
  git -C "${REPOSITORY_DIR}" check-attr --stdin "${relevant_attributes[@]}" |
  ( while IFS=: read -r line; do
      # Split the line we read into fields using ':' as delimiter
      value="${line##*: }"
      line="${line%:*}"
      attribute="${line##*: }"
      file="${line%:*}"

      if [[ "$file" != "$prev_file" && ! -z "$prev_file" ]]; then
        "$callback" "$prev_file" || (( ++failure_cnt ))
        restore_options "${relevant_attributes[@]}"
      fi

      prev_file=$file
      option_variable=option_$attribute
      if [[ -z "${!option_variable}" && "$value" == "set" ]]; then
        printf -v "$option_variable" "yes"
      fi
    done
    "$callback" "$prev_file" || (( ++failure_cnt ))
    (( failure_cnt == 0 ))
    exit $? )
  return $?
}

function command_diff()
{
  echo command_diff: done
  exit 0
}

function command_git()
{
  echo command_git: done
  exit 0
}

function command_chattr()
{
  local failure_cnt=0
  local expect_file=""
  local line attribute file
  shift

  # Collect attributes and files from command line
  local attributes=()
  local files=()
  while [[ $# -gt 0 ]]; do
    [[ $# -eq 1 ]] && expect_file="yes"
    if [[ "$expect_file" == "yes" ]]; then
      files+=("$1")
    elif [[ "$1" == "--" ]]; then
      expect_file="yes"
    else
      attributes+=("$1")
    fi
    shift
  done

  if (( ${#attributes[@]} == 0 )) ||
     (( ${#files[@]} == 0 )); then
    perror "chattr: must specify at least one attribute and one file"
  fi

  # Prepare list of files
  local i
  for i in "${!files[@]}"; do
    local path=$(realpath -s -- "${files[i]}")

    if [[ "$path" != "$REPOSITORY_DIR"* ]]; then
      path=${REPOSITORY_DIR}/Files$(system_to_repository "$path")
    fi

    if [[ ! -e "$path" ]]; then
      perror "${files[i]} does not exist in repository" non-fatal
      unset 'files[i]'
      (( ++failure_cnt ))
      continue
    fi

    if [[ -d "$path" ]]; then
      path=$path/.chez_test_gitattributes
    fi

    files[i]="$path"
  done

  # Prepare attributes
  local attr value a
  declare -A attribute_map
  for i in "${!attributes[@]}"; do
    a=${attributes[i]}
    attr=${a#+}
    attr=${attr#-}
    attr=${attr%%=*}
    if [[ "$a" == +* ]]; then
      value="set"
    elif [[ "$a" == -* ]]; then
      value="unset"
    elif [[ "$a" == *=* ]]; then
      value=${a#*=}
    else
      value="set"
    fi
    attribute_map[$attr]="$value"
  done

  git -C "${REPOSITORY_DIR}" check-attr "${!attribute_map[@]}" -- "${files[@]}" |
  while IFS=: read -r line; do
    # Split the line into fields using ':' as delimiter
    value="${line##*: }"
    line="${line%:*}"
    attribute="${line##*: }"
    file="${line%:*}"
    if [[ "${attribute_map[$attribute]}" == "$value" ]] ||
       [[ "${attribute_map[$attribute]}" == "unset"  &&
          "$value" == "unspecified" ]]; then
      verbose_message "$file: $attribute already set to ${attribute_map[$attribute]}"
    else
      verbose_message "$file: setting $attribute to ${attribute_map[$attribute]}"
      if [[ "$option_dry_run" != "yes" ]]; then
	case "${attribute_map[$attribute]}" in
	  set)   value="$attribute"    ;;
	  unset) value="-$attribute"   ;;
	  *)     value="$attribute=${attribute_map[$attribute]}" ;;
	esac
	if [[ "$file" == */.chez_test_gitattributes ]]; then
          echo "* $value" >> "${file%/*}/.gitattributes"
	else
          echo "/${file##*/} $value" >> "${file%/*}/.gitattributes"
	fi
        git -C "${REPOSITORY_DIR}" add "${file%/*}/.gitattributes"
      fi
    fi
  done

  (( failure_cnt == 0 ))
  exit
}

function prompt_user_whether_to_overwrite()
{
  [[ "$connected_to_terminal" == "no" ]] && return 1
  local response
  while true; do
    echo -n "$2 already exists. Overwrite? [y,n,q,d,a]: " > /dev/tty
    read -r response < /dev/tty
    case "$response" in
      y) return 0 ;;
      n) return 1 ;;
      q) exit 1   ;;
      d) git diff --no-index "$1" "$2" ;;
      a) user_override_overwrite="always"
         return 0 ;;
    esac
  done
}

function is_overwrite_allowed()
{
  [[ "$user_override_overwrite" == "always" ]] && return 0;

  case "$option_overwrite" in
    yes) ;&
    always) return 0 ;;
    prompt) prompt_user_whether_to_overwrite "$1" "$2" ;;
    *) return 1;;
  esac
}

function apply_single_file()
{
  local destination=$(repository_to_system "$1")

  if [[ -e "$destination" ]]; then
    if ! is_overwrite_allowed "$1" "$destination"; then
      echo "Skipping $1: already exist"
      return 0
    fi
  fi

  if [[ "$option_symbolic" == "yes" ]]; then
    verbose_message "Linking $1 to $destination"
    is_this_a_dry_run ||
    ln -sfn "$1" "$destination"
  else
    verbose_message "Copying $1 to $destination"
    is_this_a_dry_run ||
    cp "$1" "$destination"
  fi
}

function apply_single_path()
{
  local expanded_path=${1/#:/$REPOSITORY_DIR/Groups/}
        expanded_path=$(realpath -s -- "$expanded_path")

  if [[ "$expanded_path" != "$REPOSITORY_DIR"* ]]; then
    expanded_path=${REPOSITORY_DIR}/Files$(system_to_repository "$expanded_path")
  fi

  if [[ ! -e "$expanded_path" ]]; then
    perror "$1 does not exist in repository" non-fatal
    return 1
  fi

  user_override_overwrite=""

  verbose_message "Applying $1..."
  if [[ "$expanded_path" == "$REPOSITORY_DIR/Groups/"* ]]; then
    if [[ -d "$expanded_path" ]]; then
      for_each_found_file_with_options_slurped_do apply_single_file "$expanded_path" -type l -exec readlink -f {} +
    elif [[ -h "$expanded_path" ]]; then
      for_each_found_file_with_options_slurped_do apply_single_file "$(realpath -- $expanded_path)"
    else
      perror "$1 is not a file that can be applied" non-fatal
      return 1
    fi
  else
    for_each_found_file_with_options_slurped_do apply_single_file "$expanded_path" -type f
  fi

  return $?
}

function command_apply()
{
  local option_symbolic=""
  local option_overwrite=""
  local option_force=""
  local success_cnt=0 failure_cnt=0

  shift
  while [[ $# -gt 0 ]]; do
    if [[ "$1" == "-s" ]]; then
      option_symbolic="yes"
    elif [[ "$1" == "-c" || "$1" == "--copy" ]]; then
      option_symbolic="no"
    elif [[ "$1" == "-f" || "$1" == "--force" ]]; then
      option_force="yes"
    elif [[ "$1" == "-o" || "$1" == "--overwrite" ]]; then
      option_overwrite="yes"
    elif [[ "$1" == "-op" || "$1" == "--overwrite=prompt" ]]; then
      option_overwrite="prompt"
    elif [[ "$1" == "--overwrite=always" ]]; then
      option_overwrite="always"
    elif [[ "$1" == "--overwrite=never" ]]; then
      option_overwrite="never"
    elif [[ "$1" == "-v" || "$1" == "--verbose" ]]; then
      option_verbose="yes"
    elif [[ "$1" == "-n" || "$1" == "--dry-run" ]]; then
      option_dry_run="yes"
    elif [[ "$1" != -* ]]; then
      apply_single_path "$1" && (( ++success_cnt )) || (( ++failure_cnt ))
    else
      perror "unknown option $1"
    fi
    shift
  done

  if (( $success_cnt == 0 )) && (( $failure_cnt == 0 )); then
    apply_single_path "${REPOSITORY_DIR}/Files"
  elif (( $failure_cnt > 0 && $failure_cnt+$success_cnt > 1)); then
    echo "$((success_cnt+failure_cnt)) paths applied: $success_cnt success(es), $failure_cnt failure(s)"
  fi

  (( failure_cnt == 0 ))
  exit $?
}

function command_apply_check_options()
{
  shift
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -s) ;&
      -c) ;&
      -o|--overwrite) ;&
      --overwrite=always) ;&
      --overwrite=never)  ;&
      --overwrite=prompt|-op) ;&
      -v|--verbose) ;&
      -n|--dry_run) ;&
      -f|--force) : ;;
      *)
        if [[ "$1" == -* ]]; then
          perror "unknown option $1"
	fi ;;
    esac
    shift
  done
}

function ensure_repository_exists()
{
  if [[ ! -d "$REPOSITORY_DIR/.git" ]]; then
    verbose_message "Creating initial repository at $REPOSITORY_DIR"
    mkdir -p "$REPOSITORY_DIR" ||
      perror "Error creating repository directory $REPOSITORY_DIR"
    (cd "$REPOSITORY_DIR"
     mkdir -p Files
     mkdir -p Groups
     touch Files/.gitkeep Groups/.gitkeep
     git init
     echo "Chez v0.1 source repository" > .git/description
     git add Files/.gitkeep Groups/.gitkeep
     git commit -m "Initiating repository")
  fi
}

function perror_file_points_to_repository()
{
  echo "'$1' points into or is in the repository."
  # TODO: After implementing conversion to repository filename
  # add a warning "This link is not managed by Chez" if the
  # link target does not correspond to source file.
}

function add_file_to_repository()
{
  if [[ -L "$1" && ! "$option_follow_link" == "yes" ]]; then
    echo "Skipping $1: symbolic link."
    return 1
  fi

  if [[ -f "$1" ]]; then
    destination_filename=$(system_to_repository "$1")
    is_this_a_dry_run ||
    { mkdir -p "${REPOSITORY_DIR}/Files${destination_filename%/*}"
      cp "$1" "${REPOSITORY_DIR}/Files${destination_filename}" || return 1
      git -C "${REPOSITORY_DIR}" add "Files${destination_filename}"; }
    verbose_message "Copying $1 to repository"
    if [[ "$option_symbolic" == "yes" ]]; then
      is_this_a_dry_run ||
      { rm "$1"
        ln -s "${REPOSITORY_DIR}/Files${destination_filename}" "$1"; }
      verbose_message "Replacing $1 with symbolic link to repository"
    fi
  elif [[ -d "$1" ]]; then
    for_each_found_file_do add_file_to_repository "$1" -type f
  else
    echo "Skipping $1: special file."
    return 1
  fi

  return 0
}

function record_attributes_if_necessary()
{
  local attribute
  local relevant_attributes=(symbolic test)
  local path="${REPOSITORY_DIR}/Files$(system_to_repository "$1")"

  if [[ -d "$path" ]]; then
    path=$path/.chez_test_gitattributes
  fi

  git -C "${REPOSITORY_DIR}" check-attr "${relevant_attributes[@]}" -- $path |
  cut -d: -f2- |
  while IFS=: read -r attribute value; do
    option_value="option_${attribute# }"
    if [[ "$value" == " set" && "${!option_value}" != "yes" ]] ||
       [[ "$value" != " set" && "${!option_value}" == "yes" ]]; then
      [[ "$value" == " set" ]] && sign_prefix="-" || sign_prefix=""
      verbose_message "Recording attribute $sign_prefix${attribute# } for $path"
      if [[ "$option_dry_run" != "yes" ]]; then
        if [[ -d "$1" ]]; then
          echo "* $sign_prefix${attribute# }" >> "${path%/*}/.gitattributes"
        else
          echo "/${path##*/} $sign_prefix${attribute# }" >> "${path%/*}/.gitattributes"
        fi
        git -C "${REPOSITORY_DIR}" add "${path%/*}/.gitattributes"
      fi
    fi
  done
}

function add_single_path()
{
  ensure_repository_exists

  # Report error if no path specified
  if [[ -z "$1" ]]; then
    perror "No path specified!" non-fatal
    return 1
  fi

  # Report error if file is in the repository or doesn't exists
  if [[ "$(realpath -- "$1")" == "${REPOSITORY_DIR}"* ]]; then
    perror_file_points_to_repository "$1"
    return 1
  fi

  if [[ ! -e "$1" ]]; then
    perror "'$1' does not exists." non-fatal
    return 1
  fi

  if [[ ! -r "$1" ]]; then
    perror "'$1' is not readable." non-fatal
    return 1
  fi

  local absolute_path=$(realpath -s -- "$1")
  verbose_message "Adding $absolute_path to repository..."
  add_file_to_repository "$absolute_path" &&
  record_attributes_if_necessary "$absolute_path"
  return $?
}

function command_add()
{
  local option_symbolic=""
  local group=""
  local success_cnt=0 failure_cnt=0

  # Parse command line arguments
  shift
  while [[ $# -gt 0 ]]; do
    if [[ "$1" == "-s" ]]; then
      option_symbolic="yes"
    elif [[ "$1" == "-c" || "$1" == "--copy" ]]; then
      option_symbolic="no"
    elif [[ "$1" == "-L" || "$1" == "--follow-link" ]]; then
      option_follow_link="yes"
    elif [[ "$1" == "-v" || "$1" == "--verbose" ]]; then
      option_verbose="yes"
    elif [[ "$1" == "-n" || "$1" == "--dry-run" ]]; then
      option_dry_run="yes"
    elif [[ "$1" == "-g" || "$1" == "--group" ]]; then
      shift
      if [[ -z "$1" || "$1" == -* ]]; then
        perror "option -g is missing required argument"
      else
        group=$1
      fi
    elif [[ "$1" != -* ]]; then
      add_single_path "$1" && (( ++success_cnt )) || (( ++failure_cnt ))
    else
      perror "unknown option $1"
    fi
    shift
  done

  if (( $success_cnt == 0 )) && (( $failure_cnt == 0 )); then
    perror "no path specified!"
  elif (( $failure_cnt > 0 && $failure_cnt+$success_cnt > 1)); then
    echo "$((success_cnt+failure_cnt)) paths processed: $success_cnt success(es), $failure_cnt failure(s)"
  fi                                       #
                                           #
  (( failure_cnt == 0 ))
  exit $?
}

function command_add_check_options()
{
  shift
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -g|--group)
        shift
	if [[ -z "$1" || "$1" == -* ]]; then
          perror "option -g is missing required argument"
	fi ;;
      -s) ;&
      -c) ;&
      -v|--verbose) ;&
      -n|--dry-run) ;&
      -L|--follow-link) : ;;
      *)
        if [[ "$1" == -* ]]; then
          perror "unknown option $1"
	fi ;;
    esac
    shift
  done
}

function perror_unknown_option_or_command()
{
  if [[ "$1" == -* ]]; then
    echo "$arg0: Unknown option $1."
  else
    echo "$arg0: Unknown command $1."
  fi
  exit 1
}

option_follow_link=""
option_verbose=""
option_dry_run=""

# Expand short option groups
cmd_line_args=()
while [[ $# -gt 0 ]]; do
  if [[ "$1" == -[^-][^-]* ]]; then
    for (( i=1; i<${#1}; i++ )); do
      cmd_line_args+=("-${1:i:1}")
    done
  else
    cmd_line_args+=("$1")
  fi
  shift
done

set -- "${cmd_line_args[@]}"

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage   ;;
    --version)
      version ;;
    -v|--verbose)
      option_verbose="yes" ;;
    -n|--dry-run)
      option_dry_run="yes" ;;
    -L|--follow-link)
      option_follow_link="yes" ;;
    add)
      command_add_check_options "$@"
      command_add "$@"    ;;
    apply)
      command_apply_check_options "$@"
      command_apply "$@"  ;;
    diff)
      command_diff "$@"   ;;
    git)
      shift
      command_git "$@"    ;;
    status) ;&
    commit)
      command_git "$@"    ;;
    chattr)
      command_chattr "$@" ;;
    *) perror_unknown_option_or_command "$1" ;;
  esac
  shift
done

# vim: set sw=2 :
