#!/bin/bash
# Copyright (C) 2026 Zoran Loncarevic

arg0=${0##*/}
: "${REPOSITORY_DIR:=$HOME/Projects/Chez/Repository}"

function usage() {
  echo "Usage: $arg0 [options] command ..."
  exit 0
}

function version() {
  echo "$arg0 version 0.1"
  exit 0
}

function perror() {
  echo $1
  exit 1
}

function command_diff()
{
  echo command_diff: done
  exit 0
}

function command_git()
{
  echo command_git: done
  exit 0
}

function command_apply()
{
  echo command_apply: done
  exit 0
}

function ensure_repository_exists()
{
  if [[ ! -d "$REPOSITORY_DIR/.git" ]]; then
    mkdir -p "$REPOSITORY_DIR" ||
      perror "Error creating repository directory $REPOSITORY_DIR"
    (cd "$REPOSITORY_DIR"
     mkdir -p Files
     mkdir -p Groups
     touch Files/.gitkeep Groups/.gitkeep
     git init
     echo "Chez v0.1 source repository" > .git/description
     git add Files/.gitkeep Groups/.gitkeep
     git commit -m "Initiating repository")
  fi
}

function perror_file_points_to_repository()
{
  echo "'$1' points into or is in the repository."
  # TODO: After implementing conversion to repository filename
  # add a warning "This link is not managed by Chez" if the
  # link target does not correspond to source file.
  exit 1
}

function command_add()
{
  local option_symbolic=""
  local file_path=""
  local group=""

  # Parse command line arguments
  shift
  while [[ $# -gt 0 ]]; do
    if [[ "$1" == "-s" ]]; then
      option_symbolic="yes"
    elif [[ -z "$file_path" ]]; then
      file_path=$1
    else
      group=$1
    fi
    shift
  done

  ensure_repository_exists

  # Report error if file is in the repository or doesn't exists
  if [[ "$(realpath "$file_path")" == "${REPOSITORY_DIR}"* ]]; then
    perror_file_points_to_repository "$file_path"
  fi

  if [[ ! -e "$file_path" ]]; then
    perror "'$file_path' does not exists."
  fi

  if [[ ! -r "$file_path" ]]; then
    perror "'$file_path' is not readable."
  fi

  exit 0
}

function perror_unknown_option_or_command()
{
  if [[ "$1" == -* ]]; then
    echo "$arg0: Unknown option $1."
  else
    echo "$arg0: Unknown command $1."
  fi
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage   ;;
    --version)
      version ;;
    add)
      command_add "$@"    ;;
    apply)
      command_apply "$@"  ;;
    diff)
      command_diff "$@"   ;;
    git)
      shift
      command_git "$@"    ;;
    status) ;&
    commit)
      command_git "$@"    ;;
    *) perror_unknown_option_or_command "$1" ;;
  esac
  shift
done
